export default [
  {
    name: "Bronze",
    tag: "“I’m good at writing”",
    price: "₦10,000",
    discount: "- ₦0",
    product: [
      "Listening Mock Tests",
      "Listening Mock Tests",
      "Reading Mock Tests",
      "",
      "",
      "",
      "",
    ],
  },
  {
    name: "Gold",
    tag: "“I just need to pass all”",
    price: "₦15,000",
    discount: "",
    product: [
      "Listening Mock Tests",
      "Listening Mock Tests",
      "Reading Mock Tests",
      "Speaking Mock Tests",
      "Writing Mock Tests",
      "Detailed Feedbacks",
      "Notifications Channel",
    ],
  },
  {
    name: "Silver",
    tag: "“I want 8.5 in writing”",
    price: "₦10,000",
    discount: "- ₦5,000 discount",
    product: [
      "Listening Mock Tests",
      "Listening Mock Tests",
      "Reading Mock Tests",
      "Speaking Mock Tests",
      "Writing Mock Tests",
      "",
      "",
    ],
  },
];
